spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test_db?charset=utf8
    username: test_user
    password: test_user
  jpa:
    #database-platform: org.
    show-sql: true
    hibernate:
      ddl-auto: update